management:
  info:
    env:
      enabled: true
    git:
      enabled: true
    build:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: shutdown
  endpoint:
    health:
      enabled: true
      show-details: always
    beans:
      enabled: true

info:
  application:
    name: "${name}"
    group: "${group}"
    version: "${version}"